- name: Lookup rds_id
  include: lookup.yml
  when: rds_name is defined

- name: Lookup rds_parametergroup_id
  include: lookup_parametergroup.yml
  when: rds_name is defined

- name: Send request to API (apply RDS parametergroup)
  uri:
    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/configurations/{{ rds_parametergroup_id }}/apply"
    method: PUT
    body_format: json
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    status_code: 200,201,202,203
    headers:
      Content-Type: "application/json"
      X-Language: "en-us"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{ \"instance_ids\": [\"{{ rds_id }}\"] }"
  register: rds
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: rds.status == 200 or rds.status == 201 or rds.status == 202 or rds.status == 203
  changed_when: false
  when:
    - rds_id is defined
    - rds_parametergroup_id is defined

- name: Output of  rds
  debug:
    msg: "{{ rds.json }}"

