- name: Send request to API (delete RDS backup)
  uri:
    url: "{{ AUTH_URL_RDS }}/{{ OS_USER_DOMAIN_ID }}/backups/{{ rds_backup_id }}"
    method: DELETE
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
      X-Language: "en-us"
  register: rdsbackup
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: rdsbackup.status == 200
  changed_when: false
  when:
    - rds_backup_id is defined

- name: Output of rds
  debug:
    msg: "{{ rdsbackup }}"
