- name: Lookup rds_parametergroup_id
  include: lookup_parametergroup.yml
  when:
    - rds_name is defined

- name: Send request to API (delete RDS parametergroup)
  uri:
    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/configurations/{{ rds_parametergroup_id }}"
    method: DELETE
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
      X-Language: "en-us"
  register: rds
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: rds.status == 200
  changed_when: false
  when:
    - rds_parametergroup_id is defined

- name: Output of rds
  debug:
    msg: "{{ rds }}"
