- name: Lookup rds_version_id
  include: version.yml

- name: Request rds flavors from API
  uri:
#    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/flavors/{{ rds_type }}?version_name={{ rds_version.rsplit('.',1)[0] }}"
    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/flavors/{{ rds_type }}?version_name={{ rds_version }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-Language: "en-us"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: rds_flavors
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: rds_flavors.status == 200
  changed_when: false

- name: Set fact rds_flavor_id (without HA)
  set_fact:
    rds_ram: "{{ rds_ram | int // 1000 }}"
    rds_spec_code: "{{ (rds_flavors.content|from_json)|json_query('flavors[?instance_mode==`single`] |sort_by(@, &ram)|[?ram>=`' + rds_ram + '`].spec_code|[0]') }}"
  when:
    - rds_ram is defined
#    - rds_ha_enabled == false

- name: Set fact rds_spec_code (HA)
  set_fact:
    rds_spec_code: "{{ (rds_flavors.content|from_json)|json_query('flavors[?instance_mode==`ha`] |sort_by(@, &ram)|[?ram>=`' + rds_ram + '`].spec_code|[0]') }}"
  when:
    - rds_ram is defined
    - rds_ha_enabled == true

- name: Set fact rds_flavor_id (without HA)
  set_fact:
    rds_spec_code: "{{ (rds_flavors.content|from_json)|json_query('flavors[?instance_mode==`single`] |sort_by(@, &ram)|[?ram>=`' + rds_ram + '`].spec_code|[0]') }}"
  when:
    - rds_ram is defined
    - rds_ha_enabled == false

- name: debug rds_flavors.json
  debug:
    msg: "{{ rds_flavors.json }}"
  when:
    - localaction == "flavor"

- name: debug rds_spec_code
  debug:
    msg: "{{ rds_spec_code }}"
  when:
    - rds_spec_code is defined
