- name: Send request to API (list RDS onfigurations)
  uri:
    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/configurations"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
      X-Language: "en-us"
  register: rds
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: rds.status == 200
  changed_when: false

- name: Set fact rds_parametergroup_id 
  set_fact:
    rds_parametergroup_id: "{{ (rds.content|from_json)|json_query(\"configurations[?name=='\" + rds_name + \"-params'].id|[0]\") }}"
  when: rds_name is defined
