- name: Lookup rds_id
  include: lookup.yml

- name: Send request to API (restore RDS backup)
  uri:
    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/instances/recovery"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    status_code: 200,201,202,203
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
      X-Language: "en-us"
    body: "{{ lookup('template', 'restore_backup_current.json.j2')|to_json }}"
  register: rdsbackup
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: rdsbackup.status == 200 or rdsbackup.status == 201 or rdsbackup.status == 202 or rdsbackup.status == 203
  changed_when: false
  when:
    - rds_id is defined

- name: Output of rdsbackup
  debug:
    msg: "{{ rdsbackup }}"

- name: Wait a bit for job start
  pause: 
    seconds: 10

- name: Send request to API (wait for rds ACTIVE)
  uri:
    url: "{{ AUTH_URL_RDS }}/v3/{{ OS_USER_DOMAIN_ID }}/instances?id={{ rds_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
      X-Language: "en-us"
  register: rds
  retries: 300
  delay: 5
  until: ((rds.content|from_json)|json_query('instances[].status|[0]')) == 'ACTIVE'
  changed_when: false
  when:
    - rds_id is defined
    - waitfor | bool

- name: Output of rds
  debug:
    msg: "{{ rds }}"

